"""Render every prompt the audit can send, byte-exact, into one reviewable file.

    python3 -m honeybee_qc.dump_prompts --out honeybee_qc/PROMPTS.md

Generated rather than hand-written on purpose: a prompt review is only worth
anything if what you read is what actually goes over the wire. Everything below
comes from calling the real builders on real data, so it cannot drift from the
code.

The rubric-stage prompts are rendered against the planted demo rubric. The
rating-stage prompts are rendered against the real 16-exchange Gemini
conversation if its snapshot is on disk, and against a small synthetic
conversation otherwise.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from .config import DEFAULT_POLICY, POLICY_VERSION, Policy
from .demo_rating_stage import PLANTED_RUBRIC, build_task as build_rating_task
from .demo_rubric_stage import build_task as build_rubric_task
from .llm import DEFAULT_EFFORT, DEFAULT_MODEL, ClaudeCliClient, ModelRequest
from .models import ModelSubmission, Task, Turn
from .prompts import (
    COVERAGE_SCHEMA,
    CRITERION_SCHEMA,
    SYSTEM_PROMPT as RUBRIC_SYSTEM_PROMPT,
    build_coverage_prompt,
    build_criterion_prompt,
)
from .rating_prompts import (
    CRITERION_RATING_SCHEMA,
    DIMENSION_RATING_SCHEMA,
    LIKERT_SCHEMA,
    RATING_SYSTEM_PROMPT,
    build_criterion_rating_prompt,
    build_dimension_rating_prompt,
    build_likert_prompt,
)
from .rating_stages import build_rating_requests, estimate_rating_calls
from .registry import ORDER, REGISTRY
from .sources import fetch_link_transcript
from .stages import build_criterion_requests, build_coverage_request
from .taxonomies import RATING_DIMENSIONS

REAL_LINK = "https://gemini.google.com/share/d64e0a300ec0"


def _fence(text: str, lang: str = "text") -> str:
    return f"```{lang}\n{text}\n```"


def _schema(schema: dict) -> str:
    return _fence(json.dumps(schema, indent=2), "json")


def _synthetic_conversation() -> list[Turn]:
    return [
        Turn(index=1, role="user",
             text="I'm a physics teacher. Make me a short animation explaining how a "
                  "gyroscope resists changes in orientation, for high schoolers."),
        Turn(index=1, role="assistant", text="Your video is ready! 0:00 / 0:10"),
        Turn(index=2, role="user",
             text="Make the precession arrow red instead of blue so it contrasts with "
                  "the angular momentum vector."),
        Turn(index=2, role="assistant",
             text="I have updated the internal script specifications. The precession "
                  "arrow is now red, and the angular momentum vector remains blue along "
                  "the spin axis. Everything is fully configured and locked in for the "
                  "next render, including the 4K export setting you asked about."),
    ]


def _rating_task(snapshot_only: bool) -> tuple[Task, str]:
    """The real conversation if its snapshot is cached, else a synthetic stand-in."""
    policy = Policy(snapshot_dir=".honeybee_snaps")
    snap = Path(".honeybee_snaps")
    if snap.exists() and any(snap.glob("gemini_*.html")):
        transcript = fetch_link_transcript(REAL_LINK, policy, str(snap))
        if not transcript.error and transcript.turns:
            return build_rating_task(REAL_LINK, transcript), (
                f"the real {len(transcript.turns)}-turn conversation at {REAL_LINK}"
            )
    task = build_rating_task(REAL_LINK, type("T", (), {"turns": []})())
    task.model_a = ModelSubmission(
        model="A",
        final_link=REAL_LINK,
        attachments=["gyroscope_animation.mp4"],
        conversation=_synthetic_conversation(),
    )
    return task, "a synthetic 2-exchange conversation (no snapshot on disk)"


def render(out: Path) -> str:
    rubric_task = build_rubric_task()
    rating_task, rating_source = _rating_task(snapshot_only=False)
    policy = DEFAULT_POLICY

    L: list[str] = []
    add = L.append

    add("# Every prompt the audit sends")
    add("")
    add("Generated by `python3 -m honeybee_qc.dump_prompts`. Do not edit by hand: "
        "every block below is produced by calling the real prompt builders, so it "
        "matches what the CLI sends.")
    add("")
    add(f"Policy version `{POLICY_VERSION}`. Default model `{DEFAULT_MODEL}`, "
        f"effort `{DEFAULT_EFFORT}`.")
    add("")

    # ---- invocation ------------------------------------------------------
    add("## How a call is actually made")
    add("")
    add("Every call is a separate `claude` subprocess with tools disabled and a JSON "
        "schema attached. Nothing is batched: one judgment per call, always.")
    add("")
    sample = ModelRequest(
        key="example", prompt="<PROMPT GOES HERE>", schema={"type": "object"},
        system="<SYSTEM PROMPT GOES HERE>",
    )
    argv = ClaudeCliClient()._argv(sample)
    add(_fence("\n".join(argv), "text"))
    add("")
    add("`--tools \"\"` is deliberate. The predecessor engine granted Bash, Read, Glob, "
        "and Grep and let the model explore a filesystem, which made runs slow and "
        "non-reproducible. Here every piece of evidence is in the prompt, so there is "
        "nothing to explore and nothing to vary between runs.")
    add("")

    # ---- call inventory --------------------------------------------------
    add("## Call inventory for one task")
    add("")
    add("| stage | call | one per | count on a 20-criterion, 2-model task | checks |")
    add("| --- | --- | --- | --- | --- |")
    add("| rubric | criterion audit | criterion | 20 | 200, 230, 240, 250, 260 |")
    add("| rubric | coverage | task | 1 | 230, 240, 250 |")
    add("| rating | criterion rating | criterion x model | 40 | 270 |")
    add("| rating | dimension rating | dimension x model | 12 | 300 |")
    add("| rating | side-by-side Likert | task | 1 | 400 |")
    add("")
    add(f"That is 74 calls. The live run measured $0.06 per call, so roughly $4.40 per "
        f"task. `--dry-run` prints the exact count before anything is spent.")
    add("")

    # ---- rubric stage ----------------------------------------------------
    add("---")
    add("")
    add("# Stage: rubric authoring (checks 200, 230, 240, 250, 260)")
    add("")
    add("One call per criterion. Each call returns three things at once - the "
        "criterion's issues, an L1 label, and a weight - which covers all five checks "
        "without a second pass.")
    add("")
    add("## System prompt")
    add("")
    add(_fence(RUBRIC_SYSTEM_PROMPT))
    add("")
    add("## Per-criterion prompt")
    add("")
    add("Rendered for criterion C3 of the planted demo rubric. Note what is *absent*: "
        "no contributor label, no contributor weight, no contributor rating. Sibling "
        "criteria appear (so `overlapping` is detectable) but stripped of their labels "
        "and weights.")
    add("")
    target = rubric_task.rubric[2]
    add(_fence(build_criterion_prompt(rubric_task, target, policy)))
    add("")
    add("### Response schema")
    add("")
    add(_schema(CRITERION_SCHEMA))
    add("")
    add("## Coverage prompt (one per task)")
    add("")
    add("Finds requirements no criterion covers. The customer's target deliverables "
        "are the authoritative checklist, so this pass does not invent requirements.")
    add("")
    add(_fence(build_coverage_prompt(rubric_task, policy)))
    add("")
    add("### Response schema")
    add("")
    add(_schema(COVERAGE_SCHEMA))
    add("")

    # ---- rating stage ----------------------------------------------------
    add("---")
    add("")
    add("# Stage: blind rating pass (checks 270, 300, 400)")
    add("")
    add(f"Rendered against {rating_source}.")
    add("")
    add("These three checks measure distance from an independent rating, so the "
        "contributor's values are absent and `assert_blind` re-checks every prompt "
        "before it is sent. Checks 280, 310, and 450 judge the contributor's own "
        "citations and justifications and therefore need that material - which is "
        "exactly why they must be a separate pass and never share a call with these.")
    add("")
    add("Blind prompts never use the word \"contributor\" at all, so no framing can "
        "hint that a prior rating exists.")
    add("")
    add("## System prompt")
    add("")
    add(_fence(RATING_SYSTEM_PROMPT))
    add("")

    add("## Per-criterion rating prompt (check 270)")
    add("")
    artifact_criterion = next(
        c for c in rating_task.rubric
        if c.criterion_id == next(cid for cid, _, k in PLANTED_RUBRIC if k == "artifact")
    )
    add(f"Rendered for `{artifact_criterion.criterion_id}`, an artifact-dependent "
        "criterion. This is the case the abstention path exists for: the requirement "
        "is about the video, and the video is not in the transcript. Look for the "
        "`[DELIVERABLE PRODUCED HERE ...]` labels in the conversation.")
    add("")
    add(_fence(build_criterion_rating_prompt(
        rating_task, artifact_criterion, rating_task.model_a, policy)))
    add("")
    add("### Response schema")
    add("")
    add(_schema(CRITERION_RATING_SCHEMA))
    add("")

    add("## Per-dimension rating prompt (check 300)")
    add("")
    add(f"Rendered for `{RATING_DIMENSIONS[0]}`. One call per (model, dimension), so "
        f"{len(RATING_DIMENSIONS)} per model.")
    add("")
    add(_fence(build_dimension_rating_prompt(
        rating_task, RATING_DIMENSIONS[0], rating_task.model_a, policy)))
    add("")
    add("### Response schema")
    add("")
    add(_schema(DIMENSION_RATING_SCHEMA))
    add("")

    add("## Side-by-side Likert prompt (check 400)")
    add("")
    add("One call per task, carrying both conversations. The budget is split evenly so "
        "a long Model A cannot crowd out Model B and bias the comparison toward "
        "whichever was rendered first.")
    add("")
    likert_task = build_rubric_task()
    likert_task.model_a = rating_task.model_a
    likert_task.model_b = ModelSubmission(
        model="B",
        final_link="https://chatgpt.com/share/example",
        attachments=[],
        conversation=_synthetic_conversation(),
    )
    likert_task.sxs.likert = None
    likert_task.sxs.justification = ""
    add(_fence(build_likert_prompt(likert_task, policy)))
    add("")
    add("### Response schema")
    add("")
    add(_schema(LIKERT_SCHEMA))
    add("")

    # ---- guards ----------------------------------------------------------
    add("---")
    add("")
    add("# Guards that run before any prompt is sent")
    add("")
    add("**`assert_independent`** (rubric stage) refuses any prompt that binds a "
        "contributor L1 label or weight to a criterion ID on the same line. A bare "
        "label name is unavoidable because the enum lists all seven; a label attached "
        "to a criterion is the leak.")
    add("")
    add("**`assert_blind`** (rating stage) uses the contributor's justification text "
        "as a canary. It is long and distinctive, so it cannot appear in a correctly "
        "built prompt by chance, and any code path that starts pulling in contributor "
        "context will drag it along. It also rejects the framing phrases below, and "
        "the contributor's Likert value.")
    add("")
    from .rating_prompts import CONTRIBUTOR_MARKERS
    add(_fence("\n".join(CONTRIBUTOR_MARKERS)))
    add("")
    add("Both raise rather than warn. A leak biases every rate toward agreement while "
        "still producing plausible-looking numbers, which is the worst possible "
        "failure mode for an audit.")
    add("")

    # ---- what happens to the answer -------------------------------------
    add("---")
    add("")
    add("# What happens to a model's answer")
    add("")
    add("No threshold in this codebase is evaluated by a model. Models emit findings; "
        "Python counts them. Validation is strict and one-directional - a dropped "
        "finding under-reports defects, which is the safe direction, whereas accepting "
        "an invented category would put an unexplainable string in a customer's "
        "error-code column. Every drop is counted and reported.")
    add("")
    add("| answer | what happens |")
    add("| --- | --- |")
    add("| issue category not in the closed set | dropped, counted as `unknown_category` |")
    add("| issue with no `evidence` | dropped, counted as `no_evidence` |")
    add("| evidence quote not found in the rubric | dropped, counted as `unverifiable_quote` |")
    add("| two issues of the same category on one criterion | deduplicated |")
    add("| L1 label outside the 7-label enum | dropped, no 200 finding for that criterion |")
    add("| weight outside 1-5 | dropped, no 260 finding for that criterion |")
    add("| defensible weight range missing or outside 1-5 | dropped, no 260 finding; "
        "falling back to the point weight is what over-flagged 260 |")
    add("| rating outside the 1-10 scale | error; the dimension leaves the denominator |")
    add("| `cannot_determine` | abstention; leaves the denominator, count reported |")
    add("| call failed after 3 retries | criterion leaves the denominator, verdict marked low confidence |")
    add("")

    # ---- policy ----------------------------------------------------------
    add("## Thresholds the gates apply")
    add("")
    add("All inclusive. Every one of these is a field on `Policy`, not a literal "
        "buried in a gate, and `Policy.provenance()` renders the active set so any "
        "published number can be reproduced.")
    add("")
    add("| check | fails when |")
    add("| --- | --- |")
    add(f"| 200 L1 labels | >= {policy.l1_fail_rate:.0%} of labelled criteria wrong |")
    add(f"| 230 rubric quality | >= {policy.rubric_major_fail_rate:.0%} carry major issues |")
    add(f"| 240 rubric quality | >= {policy.rubric_major_moderate_fail_rate:.0%} carry major or moderate |")
    add(f"| 250 rubric quality | >= {policy.rubric_all_fail_rate:.0%} carry any issue |")
    add(f"| 260 weights | of criteria whose weight is outside the auditor's defensible range, >= {policy.weights_two_level_fail_rate:.0%} two levels outside, or >= {policy.weights_any_level_fail_rate:.0%} any levels outside |")
    add(f"| 270 rubric ratings | >= {policy.rubric_eval_fail_count} criteria rated differently, or >= {policy.rubric_eval_fail_rate:.0%} of criteria |")
    add(f"| 300 dimension ratings | >= {policy.dimension_fail_major_count} deltas of {policy.dimension_major_delta}+, or >= {policy.dimension_fail_total_count} total |")
    add(f"| 400 Likert | delta >= {policy.likert_fail_delta} points |")
    add(f"| 280 / 310 turns | >= {policy.relevant_turns_fail_count} incorrectly cited turns |")
    add("")
    add(f"Bands map to scores: fail = {policy.fail_score}, non-fail = "
        f"{policy.non_fail_score}, clean = {policy.clean_score}. Score 2 is unused and "
        "raises if emitted. Below "
        f"{policy.min_judged_ratio:.0%} of judgments surviving abstention, 270 and 300 "
        "return `not_evaluated` instead of a rate.")
    add("")

    # ---- the 21 checks ---------------------------------------------------
    add("## The 21 dimensions and where each is answered")
    add("")
    add("| id | dimension | sub-dimension | shape | how it is answered |")
    add("| --- | --- | --- | --- | --- |")
    stage_names = {
        90: "deterministic", 96: "deterministic", 100: "deterministic",
        460: "deterministic",
        200: "rubric stage", 230: "rubric stage", 240: "rubric stage",
        250: "rubric stage", 260: "rubric stage",
        270: "rating stage (blind)", 300: "rating stage (blind)",
        400: "rating stage (blind)",
        210: "blocked on the L2 taxonomy",
        80: "informed stage", 95: "informed stage", 110: "informed stage",
        220: "informed stage (second opinion)", 280: "informed stage",
        310: "informed stage", 450: "informed stage", 470: "informed stage",
    }
    for cid in ORDER:
        spec = REGISTRY[cid]
        how = stage_names.get(cid, "not implemented yet")
        add(f"| {cid} | {spec.dimension} | {spec.sub_dimension or '-'} | "
            f"{spec.shape} | {how} |")
    add("")
    add("Shape A is binary (fail or clean). Shape B can never fail a task, only "
        "report non-fail. Shape C is graded. The shape is enforced in "
        "`build_verdict`, so a Shape B check cannot emit a fail even if a model "
        "asks for one.")
    add("")

    text = "\n".join(L) + "\n"
    out.write_text(text, encoding="utf-8")
    return text


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="dump every prompt to markdown")
    ap.add_argument("--out", default="honeybee_qc/PROMPTS.md")
    args = ap.parse_args(argv)
    out = Path(args.out)
    text = render(out)
    print(f"wrote {out} ({len(text)} chars, {text.count(chr(10))} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
